openapi: 3.0.0
info:
  title: Epic Movie Quotes API
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: "https://epic-movie-quotes-api.luka-bakuridze.redberryinternship.ge"
    description: production server

paths:
  /login:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1login"
  /signup:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1signup"
  /verify/{token}:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1verify~1{token}"
  /logout:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1logout"
  /forgot-password:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1forgot-password"
  /reset-password/{token}:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1reset-password~1{token}"
  /user:
    $ref: "./_swagger/paths/user.yaml#/paths/~1user"
  /user/auth:
    $ref: "./_swagger/paths/user.yaml#/paths/~1user~1auth"
  /change-email/{token}:
    $ref: "./_swagger/paths/user.yaml#/paths/~1change-email~1{token}"
  /auth/google/redirect:
    $ref: "./_swagger/paths/socialite.yaml#/paths/~1auth~1google~1redirect"
  /auth/google/callback:
    $ref: "./_swagger/paths/socialite.yaml#/paths/~1auth~1google~1callback"

components:
  securitySchemes:
    sessionCookie:
      type: apiKey
      in: cookie
      name: epicmoviequotes_session
  schemas:
    User:
      $ref: "./_swagger/schemas/user.yaml#/components/schemas/User"
    Quote:
      $ref: "./_swagger/schemas/quote.yaml#/components/schemas/Quote"
    Movie:
      $ref: "./_swagger/schemas/movie.yaml#/components/schemas/Movie"
    Notification:
      $ref: "./_swagger/schemas/notification.yaml#/components/schemas/Notification"
    QuoteUser:
      $ref: "./_swagger/schemas/quote_user.yaml#/components/schemas/QuoteUser"
    Comment:
      $ref: "./_swagger/schemas/comment.yaml#/components/schemas/Comment"
    Genre:
      $ref: "./_swagger/schemas/genre.yaml#/components/schemas/Genre"
    GenreMovie:
      $ref: "./_swagger/schemas/genre_movie.yaml#/components/schemas/GenreMovie"
    ChangeEmail:
      $ref: "./_swagger/schemas/change_email.yaml#/components/schemas/ChangeEmail"
    ChangePassword:
      $ref: "./_swagger/schemas/change_password.yaml#/components/schemas/ChangePassword"
